language: python # this works for Linux but is an error on macOS or Windows
python:
  - "3.8"

install:
  - pip3 install --upgrade pip # all three OSes agree about 'pip3'
  - pip3 install --user numpy matplotlib scipy
  - pip3 install --user pytest coverage codecov

script: coverage run -m pytest
after_success:
  - codecov
