language: python # this works for Linux but is an error on macOS or Windows
python:
  - "3.8"

install:
  - pip install -r requirements.txt

script: coverage run -m pytest

after_success:
  - codecov
